# Site
repository: adberger/adberger.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Adrian Berger
title: DevOps Engineer

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: adberger
linkedin_username: adrian-b-726572194

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name is Adrian Berger.

  I'm living in Switzerland and currently studying computer science.

content:
  - title: Skills
    layout: list
    content:
      - title: Cloud Native
        layout: left
        description: |
          * Kubernetes
          * Helm
          * GitLab CI
          * Docker
      - title: Technologies
        layout: left
        description: |
          * Windows Server
          * Internet Information Services (IIS)
          * Apache HTTP server
          * Apache Tomcat
      - title: Programming (beginner)
        layout: left
        description: |
          * Java (Spring)
      - title: Scripting (advanced)
        layout: left
        description: |
          * PowerShell
      - title: Scripting (beginner)
        layout: left
        description: |
          * Bash
          * Ruby
          * Python

  - title: Projects
    layout: list
    content:
      - title: FC Biel-Bienne 1896
        sub_title: iOS- & Android App
        caption: co-author, up until first release (23.01.2021) of app
        link: https://www.fcbiel-bienne.ch/
        link_text: Website
        additional_links:
          - title: Play Store
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=ch.fcbielbienne.smartphoneapp
          - title: App Store
            icon: fab fa-app-store-ios
            url: https://apps.apple.com/ch/app/fc-biel-bienne-1896/id1524003452
        layout: left
        description: |
          Die FCB-App bringt dir viele Informationen rund um den Verein:
          * Push-Benachrichtigungen für News und Resultatmeldungen
          * Aktuelle Resultate, Spielplan & Tabelle
          * Informationen zu den Spielern der 1. Mannschaft
          * Übersicht über die Stadien der Gegner
          * Alle Artikel des Fanshops

  - title: Experience
    layout: list
    content:
      - title: Bedag Informatik AG
        layout: left
        link: www.bedag.ch
        sub_title: Apprentice System Specialist
        caption: 2009 - 2013
        quote: >
          Engagement, Integrität und Professionalität
        description: |
          Data center services & Software solutions for the cantons of switzerland (mainly Canton of Bern)
      - title: Bedag Informatik AG
        layout: left
        link: www.bedag.ch
        sub_title: System Specialist
        caption: 2013 - 2020
        quote: >
          Engagement, Integrität und Professionalität
        description: |
          Data center services & Software solutions for the cantons of switzerland (mainly Canton of Bern)
      - title: Bedag Informatik AG
        layout: left
        link: www.bedag.ch
        sub_title: Devops Engineer
        caption: 2020 - present
        quote: >
          Engagement, Integrität und Professionalität
        description: |
          Data center services & Software solutions for the cantons of switzerland (mainly Canton of Bern)

  - title: Education
    layout: list
    content:
      - layout: left
        title: Berner Fachhochschule
        sub_title: Technik und Informatik
        caption: 2018 - present & ongoing
        description: BSc Computer Science
      - layout: left
        title: gibb
        sub_title: Berufsfachschule Bern
        caption: 2013 - 2015
        description: Technische Berufsmaturität (Professional Baccalaureate Technical Option)
      - layout: left
        title: gibb
        sub_title: Berufsfachschule Bern
        caption: 2009 - 2013
        description: Informatiker EFZ (Apprenticeship)

  - title: Certificates & Courses
    layout: list
    content:
      - layout: left
        title: SAFe
        sub_title: Scaled Agile Framework
        description: |
          * Certified SAFe 5 Agilist
          * Leading SAFe Course (5.0)
      - layout: left
        title: edX
        description: |
          * LFS162x - Introduction to Site Reliability Engineering and DevOps
          * LFS158x - Introduction to Kubernetes
          * LFS258x - Kubernetes Fundamentals
      - layout: left
        title: Linux Professional Institute
        description: |
          * LPIC-1 - Linux-Administrator
      - layout: left
        title: Microsoft
        description: |
          * Plan and Administer SharePoint 2016 (203391 @ Digicomp)
          * Installing and Configuring Windows Server 2012 (70-410)

  - title: Interests
    layout: list
    content:
      - layout: left
        title: Outdoor
        description: |
          * Travel
          * Swimming
          * Snowboarding
      - layout: left
        title: Indoor
        description: |
          * Gaming
          * Movies/Series

  - title: Investments
    layout: list
    content:
    content:
      - layout: left
        title: Shares Portfolio
        description: |
          ![alt text](images/shares.png "Shares Portfolio")
      - layout: left
        title: Cryptos Portfolio
        description: |
          * Bitcoin
          * Etherum
          * Tezos

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-spaceship
